### ISSUE TITLE
Removing the wrong file

### ISSUE THREAD

**Issue by iparask** [Becksteinlab/Parallel-analysis-in-the-MDAnalysis-Library#1]
Hello,

it is not important, but in the DCD and NCDF scripts there is at the end a ```os.remove('...xtc',...)``` instruction.

I corrected it for my runs, but I thought I should report it.

Giannis

**Comment by mkhoshle** [comment]
Hi Giannis,

Thanks, for reporting this. I made the scripts for NCDFs and DCDs from XTCs and I think I forgot to change the .xtc to .ncdf and .dcd. Thanks for reporting this.
I modified the files and it is correct now.

Mahzad
