### ISSUE TITLE
add MPI implementation to this repo

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/Parallel-analysis-in-the-MDAnalysis-Library#2]
In the paper we said

> The complete code for benchmarking as well as an alternative implementation based on mpi4py is available from https://github.com/Becksteinlab/Parallel-analysis-in-the-MDAnalysis-Library under the MIT License.

but the MPI-based code is not here – it's actually in https://github.com/Becksteinlab/MDAnalysis-with-Dask/tree/master/MPI4py-RMSD. All relevant code should be in one place for the paper.

@mkhoshle please add `MPI4py-RMSD` to this repo.

**Comment by mkhoshle** [comment]
Done!

**Comment by orbeckst** [comment]
thanks!
